# Generated by Django 5.0 on 2025-06-03 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_recurring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], help_text='Frequency of recurrence.', max_length=10)),
                ('interval', models.PositiveIntegerField(default=1, help_text='Interval between occurrences.')),
                ('end_date', models.DateField(blank=True, help_text='Date when recurrence ends.', null=True)),
            ],
            options={
                'verbose_name': 'recurrence rule',
                'verbose_name_plural': 'recurrence rules',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Optional event description.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(help_text='Event end date and time.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Indicates if event is recurring.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Optional event location.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(help_text='Event start date and time.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Event title.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(help_text='Owner of the event.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_rule',
            field=models.OneToOneField(blank=True, help_text='Recurrence rule for recurring events.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.recurrencerule'),
        ),
    ]
