# Generated by Django 5.0 on 2025-06-03 09:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_created_at_event_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencerule',
            name='weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3), blank=True, help_text="Specific weekdays for WEEKLY recurrence (e.g., ['MON', 'WED']).", null=True, size=None),
        ),
    ]
